### ISSUE TITLE
Design UML diagrams that will show how the app is intended to work.

### ISSUE THREAD

**Issue by alexandru-balan** [alexandru-balan/Aletheia#1]
## Phase 1 -- Design & Concepts
- [x] UML diagram of app integration with Firebase
- [x] UML diagram of user flow within the app
- [x] UML digram of classes and interfaces
- [ ] UML diagram of user level mechanism

## Pahse 3 -- Commit work
